Tanay unit-tests and refactoring for NCF recommender
cnvrg/ncf-recommender pull request #5
Opened 2022-11-16 23:20 UTC by tkulkarni97

1) Refactored the 'train.py' script to make it unit-testable, for example:- added functions, extra arguments to it (local dir and configurable support for num_workers)
2) Added unit-testing scripts to it, the coverage gained is as below:
<img width="1728" alt="Screen Shot 2022-11-16 at 4 17 49 PM" src="https://user-images.githubusercontent.com/69989070/202313434-9ab608d3-2326-49f8-b904-1a3ea6620d73.png">

3) @HolzerNaama I think the dataframes defined on line 91, 102, 166 (in the refactored file, commented out) are not used anywhere, could you please check if we still require them - I will delete those if not required
4) @sabinastanescu @Ramji-Satya I don't know how the process of pushing the renewed code to market place works? Do we first merge this PR into master and then deploy to production (pushing to the marketplace)? Because of this I have been holding back to create PR's for my connector unit-tests and refactoring efforts as well

2022-11-20 08:37 UTC, HolzerNaama approved these changes

2022-11-21 15:40 UTC, orionsBeltWest requested changes
In addition, recommend running the code through pylint

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_inference/requirements.txt
> +numpy
wondering why you removed the specific version string?  Did you have issue with that version? or simply wanted to get the latest?

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_inference/unittest_train_dataset.py
> +        self.td = TrainDataset(self.ratings, self.all_item_ids)
Let's walk together through this initialization: As I am not able to follow clearly

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_inference/unittest_train_dataset.py
> +            if (user == item):
Will need to discuss

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_train/unittest_train.py
> +        # Augment train data
Wondering if the code under test provide a function to train the model as per these init lines?

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_train/unittest_train.py
> +        self.assertTrue(
Is model or trainer are bool type?

2022-11-21 15:40 UTC, orionsBeltWest commented on ncf_train/train.py
> +    warnings.simplefilter(action='ignore', category=FutureWarning)
I would still wrap all this code under a function which called from if __name__ == "__main__":

2022-11-21 19:51 UTC, jedwards-habana approved these changes
License information is in place. LGTM.

2022-11-21 23:38 UTC, orionsBeltWest approved these changes
agreed that requested changes to be added in future pr

2022-11-21 23:38 UTC, orionsBeltWest commented on ncf_inference/unittest_train_dataset.py
> +    @classmethod
Please add doc string to document this function activity as discussed.

2022-11-21 23:38 UTC, orionsBeltWest commented on ncf_inference/unittest_train_dataset.py
> +        )
add rest case for predict

2022-11-21 23:38 UTC, orionsBeltWest commented on ncf_inference/unittest_train_dataset.py
> +    @classmethod
agreed to be added in future pr

2022-11-22 00:02 UTC, tkulkarni97 commented on ncf_inference/unittest_train_dataset.py
> +    @classmethod
@orionsBeltWest Yes, added the docstring to setUpClass as well as the helper function below as we discussed.

2022-11-28 16:47 UTC, merged